#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
CREATE USER kamka_user;
ALTER USER kamka_user WITH PASSWORD 'kamkapassword';
GRANT ALL ON DATABASE "$POSTGRES_DB" TO kamka_user;
GRANT ALL PRIVILEGES ON DATABASE "$POSTGRES_DB" TO kamka_user;
GRANT ALL PRIVILEGES ON SCHEMA public TO kamka_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO kamka_user;
EOSQL
