sonar.projectKey=OmarChouchane_kamka-cloudops-platform
sonar.projectName=Kamka CloudOps Platform
sonar.organization=omarchouchane
sonar.sources=app/backend/src,app/frontend/src
sonar.exclusions=**/node_modules/**,**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
