name: Kamka CI + GHCR

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Build backend image
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/kamka-backend:latest ./app/backend

      - name: Build frontend image
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/kamka-frontend:latest ./app/frontend

      - name: Push backend image
        run: |
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/kamka-backend:latest

      - name: Push frontend image
        run: |
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/kamka-frontend:latest
          